# Generated by Django 2.1.3 on 2018-11-12 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=10, unique=True)),
                ('is_driver', models.BooleanField(default=False)),
                ('car_model', models.CharField(max_length=20)),
                ('car_number', models.CharField(max_length=10)),
                ('option', models.CharField(choices=[(1, 'sharing'), (2, 'personal'), (3, 'free')], default=3, max_length=8)),
                ('seats_booked', models.IntegerField(default=0)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RideHistory',
            fields=[
                ('ride_id', models.AutoField(primary_key=True, serialize=False)),
                ('ride_from', models.CharField(max_length=60)),
                ('ride_to', models.CharField(max_length=60)),
                ('ride_time', models.DateTimeField(auto_now_add=True)),
                ('complete', models.BooleanField(default=False)),
                ('share', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='cab_app.Register')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='cab_app.Register')),
            ],
        ),
    ]
