# Generated by Django 2.1.3 on 2018-11-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cab_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='option',
            new_name='booking_status',
        ),
    ]
